# Generated by Django 5.0.7 on 2024-07-18 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manicurista',
            fields=[
                ('idManicurista', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=12)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idCita', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCita', models.DateField()),
                ('horaCita', models.TimeField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_manager.cliente')),
                ('idManicurista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ohlala_app.manicurista')),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ohlala_app.servicio')),
            ],
        ),
    ]
