# Generated by Django 5.0.7 on 2024-07-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0002_cliente_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='last_login',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
