# Generated by Django 5.0.7 on 2024-07-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0003_remove_cliente_last_login_cuenta_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='last_login',
        ),
    ]
